#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AngryNinjas.Resource", IsApplication=true)]

namespace AngryNinjas
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ouya_icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int allow = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int application_error = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int buy_button = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int check_license = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int checking_license = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dont_allow = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int quit_button = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int retry_button = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int unlicensed_dialog_body = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int unlicensed_dialog_retry_body = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int unlicensed_dialog_title = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_NoTitleBar = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
